// Copyright 2020 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. (editesyntax = "proto3";

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/survey/fhir.proto

package survey

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FHIR_CreateFHIRSurvey_FullMethodName        = "/ondewo.survey.FHIR/CreateFHIRSurvey"
	FHIR_GetFHIRSurveyAnswers_FullMethodName    = "/ondewo.survey.FHIR/GetFHIRSurveyAnswers"
	FHIR_GetAllFHIRSurveyAnswers_FullMethodName = "/ondewo.survey.FHIR/GetAllFHIRSurveyAnswers"
)

// FHIRClient is the client API for FHIR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FHIRClient interface {
	// Create a Survey from FHIR format and an empty NLU Agent for it
	CreateFHIRSurvey(ctx context.Context, in *CreateFHIRSurveyRequest, opts ...grpc.CallOption) (*Survey, error)
	// Get Survey Answers on FHIR format
	GetFHIRSurveyAnswers(ctx context.Context, in *GetSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyFHIRAnswersResponse, error)
	// Get all Survey Answers on FHIR format
	GetAllFHIRSurveyAnswers(ctx context.Context, in *GetAllSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyFHIRAnswersResponse, error)
}

type fHIRClient struct {
	cc grpc.ClientConnInterface
}

func NewFHIRClient(cc grpc.ClientConnInterface) FHIRClient {
	return &fHIRClient{cc}
}

func (c *fHIRClient) CreateFHIRSurvey(ctx context.Context, in *CreateFHIRSurveyRequest, opts ...grpc.CallOption) (*Survey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Survey)
	err := c.cc.Invoke(ctx, FHIR_CreateFHIRSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fHIRClient) GetFHIRSurveyAnswers(ctx context.Context, in *GetSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyFHIRAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyFHIRAnswersResponse)
	err := c.cc.Invoke(ctx, FHIR_GetFHIRSurveyAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fHIRClient) GetAllFHIRSurveyAnswers(ctx context.Context, in *GetAllSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyFHIRAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyFHIRAnswersResponse)
	err := c.cc.Invoke(ctx, FHIR_GetAllFHIRSurveyAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FHIRServer is the server API for FHIR service.
// All implementations must embed UnimplementedFHIRServer
// for forward compatibility.
type FHIRServer interface {
	// Create a Survey from FHIR format and an empty NLU Agent for it
	CreateFHIRSurvey(context.Context, *CreateFHIRSurveyRequest) (*Survey, error)
	// Get Survey Answers on FHIR format
	GetFHIRSurveyAnswers(context.Context, *GetSurveyAnswersRequest) (*SurveyFHIRAnswersResponse, error)
	// Get all Survey Answers on FHIR format
	GetAllFHIRSurveyAnswers(context.Context, *GetAllSurveyAnswersRequest) (*SurveyFHIRAnswersResponse, error)
	mustEmbedUnimplementedFHIRServer()
}

// UnimplementedFHIRServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFHIRServer struct{}

func (UnimplementedFHIRServer) CreateFHIRSurvey(context.Context, *CreateFHIRSurveyRequest) (*Survey, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFHIRSurvey not implemented")
}
func (UnimplementedFHIRServer) GetFHIRSurveyAnswers(context.Context, *GetSurveyAnswersRequest) (*SurveyFHIRAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFHIRSurveyAnswers not implemented")
}
func (UnimplementedFHIRServer) GetAllFHIRSurveyAnswers(context.Context, *GetAllSurveyAnswersRequest) (*SurveyFHIRAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllFHIRSurveyAnswers not implemented")
}
func (UnimplementedFHIRServer) mustEmbedUnimplementedFHIRServer() {}
func (UnimplementedFHIRServer) testEmbeddedByValue()              {}

// UnsafeFHIRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FHIRServer will
// result in compilation errors.
type UnsafeFHIRServer interface {
	mustEmbedUnimplementedFHIRServer()
}

func RegisterFHIRServer(s grpc.ServiceRegistrar, srv FHIRServer) {
	// If the following call panics, it indicates UnimplementedFHIRServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FHIR_ServiceDesc, srv)
}

func _FHIR_CreateFHIRSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFHIRSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FHIRServer).CreateFHIRSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FHIR_CreateFHIRSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FHIRServer).CreateFHIRSurvey(ctx, req.(*CreateFHIRSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FHIR_GetFHIRSurveyAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurveyAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FHIRServer).GetFHIRSurveyAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FHIR_GetFHIRSurveyAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FHIRServer).GetFHIRSurveyAnswers(ctx, req.(*GetSurveyAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FHIR_GetAllFHIRSurveyAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSurveyAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FHIRServer).GetAllFHIRSurveyAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FHIR_GetAllFHIRSurveyAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FHIRServer).GetAllFHIRSurveyAnswers(ctx, req.(*GetAllSurveyAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FHIR_ServiceDesc is the grpc.ServiceDesc for FHIR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FHIR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.survey.FHIR",
	HandlerType: (*FHIRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFHIRSurvey",
			Handler:    _FHIR_CreateFHIRSurvey_Handler,
		},
		{
			MethodName: "GetFHIRSurveyAnswers",
			Handler:    _FHIR_GetFHIRSurveyAnswers_Handler,
		},
		{
			MethodName: "GetAllFHIRSurveyAnswers",
			Handler:    _FHIR_GetAllFHIRSurveyAnswers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ondewo/survey/fhir.proto",
}
