// Copyright 2020 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. (editesyntax = "proto3";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: ondewo/survey/fhir.proto

package survey

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFHIRSurveyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FHIR questionnaire on a gRPC Struct format
	FhirQuestionnaire *structpb.Struct `protobuf:"bytes,1,opt,name=fhir_questionnaire,json=fhirQuestionnaire,proto3" json:"fhir_questionnaire,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateFHIRSurveyRequest) Reset() {
	*x = CreateFHIRSurveyRequest{}
	mi := &file_ondewo_survey_fhir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFHIRSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFHIRSurveyRequest) ProtoMessage() {}

func (x *CreateFHIRSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_fhir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFHIRSurveyRequest.ProtoReflect.Descriptor instead.
func (*CreateFHIRSurveyRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_fhir_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFHIRSurveyRequest) GetFhirQuestionnaire() *structpb.Struct {
	if x != nil {
		return x.FhirQuestionnaire
	}
	return nil
}

type SurveyFHIRAnswersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project identifier for this survey. Equal to the parent of the corresponding Agent.
	// Format: `projects/<Project ID>/agent`.
	SurveyId                   string             `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	FhirQuestionnaireResponses []*structpb.Struct `protobuf:"bytes,2,rep,name=fhir_questionnaire_responses,json=fhirQuestionnaireResponses,proto3" json:"fhir_questionnaire_responses,omitempty"` // all requested answers
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SurveyFHIRAnswersResponse) Reset() {
	*x = SurveyFHIRAnswersResponse{}
	mi := &file_ondewo_survey_fhir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyFHIRAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyFHIRAnswersResponse) ProtoMessage() {}

func (x *SurveyFHIRAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_fhir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyFHIRAnswersResponse.ProtoReflect.Descriptor instead.
func (*SurveyFHIRAnswersResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_fhir_proto_rawDescGZIP(), []int{1}
}

func (x *SurveyFHIRAnswersResponse) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *SurveyFHIRAnswersResponse) GetFhirQuestionnaireResponses() []*structpb.Struct {
	if x != nil {
		return x.FhirQuestionnaireResponses
	}
	return nil
}

var File_ondewo_survey_fhir_proto protoreflect.FileDescriptor

const file_ondewo_survey_fhir_proto_rawDesc = "" +
	"\n" +
	"\x18ondewo/survey/fhir.proto\x12\rondewo.survey\x1a\x1cgoogle/api/annotations.proto\x1a\x1aondewo/survey/survey.proto\x1a\x1cgoogle/protobuf/struct.proto\"a\n" +
	"\x17CreateFHIRSurveyRequest\x12F\n" +
	"\x12fhir_questionnaire\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x11fhirQuestionnaire\"\x93\x01\n" +
	"\x19SurveyFHIRAnswersResponse\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\x12Y\n" +
	"\x1cfhir_questionnaire_responses\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x1afhirQuestionnaireResponses2\xb5\x03\n" +
	"\x04FHIR\x12j\n" +
	"\x10CreateFHIRSurvey\x12&.ondewo.survey.CreateFHIRSurveyRequest\x1a\x15.ondewo.survey.Survey\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/fhir_survey\x12\xa3\x01\n" +
	"\x14GetFHIRSurveyAnswers\x12&.ondewo.survey.GetSurveyAnswersRequest\x1a(.ondewo.survey.SurveyFHIRAnswersResponse\"9\x82\xd3\xe4\x93\x023\x121/survey/{survey_id=*}/fhir_answers/{session_id=*}\x12\x9a\x01\n" +
	"\x17GetAllFHIRSurveyAnswers\x12).ondewo.survey.GetAllSurveyAnswersRequest\x1a(.ondewo.survey.SurveyFHIRAnswersResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/survey/{survey_id=*}/fhir_answersb\x06proto3"

var (
	file_ondewo_survey_fhir_proto_rawDescOnce sync.Once
	file_ondewo_survey_fhir_proto_rawDescData []byte
)

func file_ondewo_survey_fhir_proto_rawDescGZIP() []byte {
	file_ondewo_survey_fhir_proto_rawDescOnce.Do(func() {
		file_ondewo_survey_fhir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ondewo_survey_fhir_proto_rawDesc), len(file_ondewo_survey_fhir_proto_rawDesc)))
	})
	return file_ondewo_survey_fhir_proto_rawDescData
}

var file_ondewo_survey_fhir_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ondewo_survey_fhir_proto_goTypes = []any{
	(*CreateFHIRSurveyRequest)(nil),    // 0: ondewo.survey.CreateFHIRSurveyRequest
	(*SurveyFHIRAnswersResponse)(nil),  // 1: ondewo.survey.SurveyFHIRAnswersResponse
	(*structpb.Struct)(nil),            // 2: google.protobuf.Struct
	(*GetSurveyAnswersRequest)(nil),    // 3: ondewo.survey.GetSurveyAnswersRequest
	(*GetAllSurveyAnswersRequest)(nil), // 4: ondewo.survey.GetAllSurveyAnswersRequest
	(*Survey)(nil),                     // 5: ondewo.survey.Survey
}
var file_ondewo_survey_fhir_proto_depIdxs = []int32{
	2, // 0: ondewo.survey.CreateFHIRSurveyRequest.fhir_questionnaire:type_name -> google.protobuf.Struct
	2, // 1: ondewo.survey.SurveyFHIRAnswersResponse.fhir_questionnaire_responses:type_name -> google.protobuf.Struct
	0, // 2: ondewo.survey.FHIR.CreateFHIRSurvey:input_type -> ondewo.survey.CreateFHIRSurveyRequest
	3, // 3: ondewo.survey.FHIR.GetFHIRSurveyAnswers:input_type -> ondewo.survey.GetSurveyAnswersRequest
	4, // 4: ondewo.survey.FHIR.GetAllFHIRSurveyAnswers:input_type -> ondewo.survey.GetAllSurveyAnswersRequest
	5, // 5: ondewo.survey.FHIR.CreateFHIRSurvey:output_type -> ondewo.survey.Survey
	1, // 6: ondewo.survey.FHIR.GetFHIRSurveyAnswers:output_type -> ondewo.survey.SurveyFHIRAnswersResponse
	1, // 7: ondewo.survey.FHIR.GetAllFHIRSurveyAnswers:output_type -> ondewo.survey.SurveyFHIRAnswersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ondewo_survey_fhir_proto_init() }
func file_ondewo_survey_fhir_proto_init() {
	if File_ondewo_survey_fhir_proto != nil {
		return
	}
	file_ondewo_survey_survey_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ondewo_survey_fhir_proto_rawDesc), len(file_ondewo_survey_fhir_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ondewo_survey_fhir_proto_goTypes,
		DependencyIndexes: file_ondewo_survey_fhir_proto_depIdxs,
		MessageInfos:      file_ondewo_survey_fhir_proto_msgTypes,
	}.Build()
	File_ondewo_survey_fhir_proto = out.File
	file_ondewo_survey_fhir_proto_goTypes = nil
	file_ondewo_survey_fhir_proto_depIdxs = nil
}
