// Copyright 2020 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. (editesyntax = "proto3";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.32.0
// source: ondewo/survey/survey.proto

package survey

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumeration of (some of) the subflows which are created by default
// This can be used to "switch off" particular subflows when creating an agent during CreateSurvey
// Subflows are defined as one of the following:
//   - sequences of intents A -> B_1, ..., B_n -> ... -> Z_1, ..., Z_m which are linked by context relationships
//     such that the first intent in the sequence can always be triggered
//   - single intents which can always be triggered
type SubFlow int32

const (
	// Not specified. This value should be never used.
	SubFlow_SUBFLOW_UNSPECIFIED SubFlow = 0
	// The subflow allowing the user to inquire whether s/he is talking to a bot
	SubFlow_BOT SubFlow = 1
	// The subflow allowing the user to inquire about the legal entity
	SubFlow_LEGAL_ENTITY SubFlow = 2
	// The subflow allowing the user to inquire about the postal address
	SubFlow_POSTAL_ADDRESS SubFlow = 3
	// The subflow allowing the user to inquire about the email address
	SubFlow_EMAIL_ADDRESS SubFlow = 4
	// The subflow allowing the user to inquire about the phone number
	SubFlow_PHONE_NUMBER SubFlow = 5
	// The subflow allowing the user to inquire about the phone hours
	SubFlow_PHONE_HOURS SubFlow = 6
	// The subflow allowing the user to inquire about the expected duration of the survey
	SubFlow_EXPECTED_DURATION SubFlow = 7
	// The subflow allowing the user to inquire about the purpose of the survey
	SubFlow_PURPOSE SubFlow = 8
)

// Enum value maps for SubFlow.
var (
	SubFlow_name = map[int32]string{
		0: "SUBFLOW_UNSPECIFIED",
		1: "BOT",
		2: "LEGAL_ENTITY",
		3: "POSTAL_ADDRESS",
		4: "EMAIL_ADDRESS",
		5: "PHONE_NUMBER",
		6: "PHONE_HOURS",
		7: "EXPECTED_DURATION",
		8: "PURPOSE",
	}
	SubFlow_value = map[string]int32{
		"SUBFLOW_UNSPECIFIED": 0,
		"BOT":                 1,
		"LEGAL_ENTITY":        2,
		"POSTAL_ADDRESS":      3,
		"EMAIL_ADDRESS":       4,
		"PHONE_NUMBER":        5,
		"PHONE_HOURS":         6,
		"EXPECTED_DURATION":   7,
		"PURPOSE":             8,
	}
)

func (x SubFlow) Enum() *SubFlow {
	p := new(SubFlow)
	*p = x
	return p
}

func (x SubFlow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubFlow) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_survey_survey_proto_enumTypes[0].Descriptor()
}

func (SubFlow) Type() protoreflect.EnumType {
	return &file_ondewo_survey_survey_proto_enumTypes[0]
}

func (x SubFlow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubFlow.Descriptor instead.
func (SubFlow) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{0}
}

type Survey_AgentStatus int32

const (
	Survey_TO_BE_INITIALIZED Survey_AgentStatus = 0
	Survey_UPDATED           Survey_AgentStatus = 1
	Survey_UPDATING          Survey_AgentStatus = 2
	Survey_OUTDATED          Survey_AgentStatus = 3
)

// Enum value maps for Survey_AgentStatus.
var (
	Survey_AgentStatus_name = map[int32]string{
		0: "TO_BE_INITIALIZED",
		1: "UPDATED",
		2: "UPDATING",
		3: "OUTDATED",
	}
	Survey_AgentStatus_value = map[string]int32{
		"TO_BE_INITIALIZED": 0,
		"UPDATED":           1,
		"UPDATING":          2,
		"OUTDATED":          3,
	}
)

func (x Survey_AgentStatus) Enum() *Survey_AgentStatus {
	p := new(Survey_AgentStatus)
	*p = x
	return p
}

func (x Survey_AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Survey_AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ondewo_survey_survey_proto_enumTypes[1].Descriptor()
}

func (Survey_AgentStatus) Type() protoreflect.EnumType {
	return &file_ondewo_survey_survey_proto_enumTypes[1]
}

func (x Survey_AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Survey_AgentStatus.Descriptor instead.
func (Survey_AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{0, 0}
}

type Survey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project identifier for this survey. Equal to the parent of the corresponding Agent.
	// Format: `projects/<Project ID>/agent`.
	// Read-only in the Survey message (assigned by the back-end)
	SurveyId string `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	// Required. The (human readable) name of this survey
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Required. The language of the agent created for the survey.
	// This is also the only supported language of the agent.
	LanguageCode string `protobuf:"bytes,3,opt,name=language_code,json=languageCode,proto3" json:"language_code,omitempty"` // ISO 639-1 language code
	// Required. List of questions to be asked during the survey.
	Questions []*Question `protobuf:"bytes,7,rep,name=questions,proto3" json:"questions,omitempty"`
	// Required. Information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
	SurveyInfo *SurveyInfo `protobuf:"bytes,8,opt,name=survey_info,json=surveyInfo,proto3" json:"survey_info,omitempty"`
	// Optional. List of subflows excluded for this survey.
	ExcludeSubflows []SubFlow `protobuf:"varint,9,rep,packed,name=exclude_subflows,json=excludeSubflows,proto3,enum=ondewo.survey.SubFlow" json:"exclude_subflows,omitempty"`
	// Current status of the NLU Agent respecting to the Survey
	Status        Survey_AgentStatus `protobuf:"varint,10,opt,name=status,proto3,enum=ondewo.survey.Survey_AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Survey) Reset() {
	*x = Survey{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Survey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Survey) ProtoMessage() {}

func (x *Survey) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Survey.ProtoReflect.Descriptor instead.
func (*Survey) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{0}
}

func (x *Survey) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *Survey) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Survey) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *Survey) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *Survey) GetSurveyInfo() *SurveyInfo {
	if x != nil {
		return x.SurveyInfo
	}
	return nil
}

func (x *Survey) GetExcludeSubflows() []SubFlow {
	if x != nil {
		return x.ExcludeSubflows
	}
	return nil
}

func (x *Survey) GetStatus() Survey_AgentStatus {
	if x != nil {
		return x.Status
	}
	return Survey_TO_BE_INITIALIZED
}

// Collect information about the entity behind the survey, the purpose of the survey, legal stuff, etc.
// This is needed to generate meaningful messages and training data for some of the auto-generated intents.
type SurveyInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required unless SubFlow.LEGAL_ENTITY is deselected.
	// The legal entity (company, research institute, etc.) on whose behalf the survey is performed
	LegalEntity string `protobuf:"bytes,1,opt,name=legal_entity,json=legalEntity,proto3" json:"legal_entity,omitempty"`
	// Required unless SubFlow.POSTAL_ADDRESS is deselected.
	// The postal address to which callees can direct any requests.
	PostalAddress string `protobuf:"bytes,2,opt,name=postal_address,json=postalAddress,proto3" json:"postal_address,omitempty"`
	// Required unless SubFlow.EMAIL_ADDRESS is deselected.
	// The email address to which callees can direct any requests.
	EmailAddress string `protobuf:"bytes,3,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	// Required unless SubFlow.PHONE_NUMBER is deselected.
	// The phone number to which callees can direct any requests.
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// Required unless SubFlow.PHONE_HOURS is deselected.
	// The phone hours during which callees can call (in pronounceable form).
	PhoneHours string `protobuf:"bytes,5,opt,name=phone_hours,json=phoneHours,proto3" json:"phone_hours,omitempty"`
	// Required unless SubFlow.EXPECTED_DURATION is deselected.
	// The expected duration of the survey (in pronounceable form)
	ExpectedDuration string `protobuf:"bytes,6,opt,name=expected_duration,json=expectedDuration,proto3" json:"expected_duration,omitempty"`
	// Required unless SubFlow.PURPOSE is deselected.
	// An explanation regarding the purpose of the survey (in pronounceable form)
	Purpose string `protobuf:"bytes,7,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Required.
	// A one-word explanation of the survey topic (in pronounceable form)
	Topic string `protobuf:"bytes,8,opt,name=topic,proto3" json:"topic,omitempty"`
	// Required.
	// A pronounceable explanation of the legal implications of participating in the survey.
	// For example:
	//  "Your answers during this survey will be stored anonymously for the next two years and then deleted."
	// Should be formulated such that the agent can afterwards ask for the consent of the user.
	// Example for how the agent could continue: "Are you willing to participate in this survey?"
	LegalDisclaimer string `protobuf:"bytes,9,opt,name=legal_disclaimer,json=legalDisclaimer,proto3" json:"legal_disclaimer,omitempty"`
	// Optional.
	// Defaults to False. Allows the definition of a survey as anonymous or not.
	// If the survey is not anonymous, the name of the people as well as their number will be recorded
	Anonymous     bool `protobuf:"varint,10,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyInfo) Reset() {
	*x = SurveyInfo{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyInfo) ProtoMessage() {}

func (x *SurveyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyInfo.ProtoReflect.Descriptor instead.
func (*SurveyInfo) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{1}
}

func (x *SurveyInfo) GetLegalEntity() string {
	if x != nil {
		return x.LegalEntity
	}
	return ""
}

func (x *SurveyInfo) GetPostalAddress() string {
	if x != nil {
		return x.PostalAddress
	}
	return ""
}

func (x *SurveyInfo) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *SurveyInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SurveyInfo) GetPhoneHours() string {
	if x != nil {
		return x.PhoneHours
	}
	return ""
}

func (x *SurveyInfo) GetExpectedDuration() string {
	if x != nil {
		return x.ExpectedDuration
	}
	return ""
}

func (x *SurveyInfo) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *SurveyInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SurveyInfo) GetLegalDisclaimer() string {
	if x != nil {
		return x.LegalDisclaimer
	}
	return ""
}

func (x *SurveyInfo) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

type Question struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Question:
	//
	//	*Question_OpenQuestion
	//	*Question_SingleChoiceQuestion
	//	*Question_MultipleChoiceQuestion
	//	*Question_ScaleQuestion
	//	*Question_SingleParameterQuestion
	//	*Question_MultipleParameterQuestion
	Question      isQuestion_Question `protobuf_oneof:"question"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{2}
}

func (x *Question) GetQuestion() isQuestion_Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *Question) GetOpenQuestion() *OpenQuestion {
	if x != nil {
		if x, ok := x.Question.(*Question_OpenQuestion); ok {
			return x.OpenQuestion
		}
	}
	return nil
}

func (x *Question) GetSingleChoiceQuestion() *SingleChoiceQuestion {
	if x != nil {
		if x, ok := x.Question.(*Question_SingleChoiceQuestion); ok {
			return x.SingleChoiceQuestion
		}
	}
	return nil
}

func (x *Question) GetMultipleChoiceQuestion() *MultipleChoiceQuestion {
	if x != nil {
		if x, ok := x.Question.(*Question_MultipleChoiceQuestion); ok {
			return x.MultipleChoiceQuestion
		}
	}
	return nil
}

func (x *Question) GetScaleQuestion() *ScaleQuestion {
	if x != nil {
		if x, ok := x.Question.(*Question_ScaleQuestion); ok {
			return x.ScaleQuestion
		}
	}
	return nil
}

func (x *Question) GetSingleParameterQuestion() *SingleParameterQuestion {
	if x != nil {
		if x, ok := x.Question.(*Question_SingleParameterQuestion); ok {
			return x.SingleParameterQuestion
		}
	}
	return nil
}

func (x *Question) GetMultipleParameterQuestion() *MultipleParameterQuestion {
	if x != nil {
		if x, ok := x.Question.(*Question_MultipleParameterQuestion); ok {
			return x.MultipleParameterQuestion
		}
	}
	return nil
}

type isQuestion_Question interface {
	isQuestion_Question()
}

type Question_OpenQuestion struct {
	OpenQuestion *OpenQuestion `protobuf:"bytes,1,opt,name=open_question,json=openQuestion,proto3,oneof"`
}

type Question_SingleChoiceQuestion struct {
	SingleChoiceQuestion *SingleChoiceQuestion `protobuf:"bytes,2,opt,name=single_choice_question,json=singleChoiceQuestion,proto3,oneof"`
}

type Question_MultipleChoiceQuestion struct {
	MultipleChoiceQuestion *MultipleChoiceQuestion `protobuf:"bytes,3,opt,name=multiple_choice_question,json=multipleChoiceQuestion,proto3,oneof"`
}

type Question_ScaleQuestion struct {
	ScaleQuestion *ScaleQuestion `protobuf:"bytes,4,opt,name=scale_question,json=scaleQuestion,proto3,oneof"` // convenience wrapper around a SingleChoiceQuestion
}

type Question_SingleParameterQuestion struct {
	SingleParameterQuestion *SingleParameterQuestion `protobuf:"bytes,5,opt,name=single_parameter_question,json=singleParameterQuestion,proto3,oneof"`
}

type Question_MultipleParameterQuestion struct {
	MultipleParameterQuestion *MultipleParameterQuestion `protobuf:"bytes,6,opt,name=multiple_parameter_question,json=multipleParameterQuestion,proto3,oneof"`
}

func (*Question_OpenQuestion) isQuestion_Question() {}

func (*Question_SingleChoiceQuestion) isQuestion_Question() {}

func (*Question_MultipleChoiceQuestion) isQuestion_Question() {}

func (*Question_ScaleQuestion) isQuestion_Question() {}

func (*Question_SingleParameterQuestion) isQuestion_Question() {}

func (*Question_MultipleParameterQuestion) isQuestion_Question() {}

// A question to which any kind of reply can be given and recorded
// fixme: not working yet
type OpenQuestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text which introduces the question (should be pronounceable)
	QuestionText  string `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenQuestion) Reset() {
	*x = OpenQuestion{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenQuestion) ProtoMessage() {}

func (x *OpenQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenQuestion.ProtoReflect.Descriptor instead.
func (*OpenQuestion) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{3}
}

func (x *OpenQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

// A question for which exactly one out of a predefined set of options is expected as answer
// Example: SingleChoiceQuestion(
//
//	question_text='Who is your favorite movie hero?',
//	choices=[
//	    Choice(synonyms=['Bond', 'James Bond']),
//	    Choice(synonyms=['Batman']),
//	    Choice(synonyms=['Superman', 'Clark Kent']),
//	    ]
//	)
type SingleChoiceQuestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text which introduces the question (should be pronounceable)
	QuestionText string `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	// List of choices which are accepted for this question
	// Each Choice is represented by lists of synonyms.
	// Note: needs to contain at least 2 choices
	Choices       []*Choice `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleChoiceQuestion) Reset() {
	*x = SingleChoiceQuestion{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleChoiceQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleChoiceQuestion) ProtoMessage() {}

func (x *SingleChoiceQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleChoiceQuestion.ProtoReflect.Descriptor instead.
func (*SingleChoiceQuestion) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{4}
}

func (x *SingleChoiceQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *SingleChoiceQuestion) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

// A question for which exactly one or more out of a predefined set of options are expected as answers
// Example: MultipleChoiceQuestion(
//
//	question_text='Which colors do you like?',
//	choices=[
//	    Choice(synonyms=['red', 'reddisch']),
//	    Choice(synonyms=['blue', 'blueish']),
//	    Choice(synonyms=['yellow']),
//	    ]
//	 )
type MultipleChoiceQuestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text which introduces the question (should be pronounceable)
	QuestionText string `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	// List of choices which are accepted for this question
	// Each Choice is represented by lists of synonyms.
	// Note: needs to contain at least 2 choices
	Choices       []*Choice `protobuf:"bytes,2,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleChoiceQuestion) Reset() {
	*x = MultipleChoiceQuestion{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleChoiceQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleChoiceQuestion) ProtoMessage() {}

func (x *MultipleChoiceQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleChoiceQuestion.ProtoReflect.Descriptor instead.
func (*MultipleChoiceQuestion) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{5}
}

func (x *MultipleChoiceQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *MultipleChoiceQuestion) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

// A question for which an answer on a user-defined scale is expected
type ScaleQuestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text which introduces the question (should be pronounceable)
	QuestionText  string                    `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	MinValue      *ScaleQuestion_ScaleValue `protobuf:"bytes,2,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	MaxValue      *ScaleQuestion_ScaleValue `protobuf:"bytes,3,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleQuestion) Reset() {
	*x = ScaleQuestion{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleQuestion) ProtoMessage() {}

func (x *ScaleQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleQuestion.ProtoReflect.Descriptor instead.
func (*ScaleQuestion) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{6}
}

func (x *ScaleQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *ScaleQuestion) GetMinValue() *ScaleQuestion_ScaleValue {
	if x != nil {
		return x.MinValue
	}
	return nil
}

func (x *ScaleQuestion) GetMaxValue() *ScaleQuestion_ScaleValue {
	if x != nil {
		return x.MaxValue
	}
	return nil
}

// SingleParameterQuestion defines a question which prompts the user for one entity of a particular type
// Example: SingleParameterQuestion(question_text='How old are you?', parameter_type='sys.number')
type SingleParameterQuestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text which introduces the question (should be pronounceable)
	QuestionText string `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	// The display name of the entity (type) which is accepted as an answer to this question
	// Note: the corresponding entity_type must exist (system entity type) and is not automatically created
	ParameterType string `protobuf:"bytes,2,opt,name=parameter_type,json=parameterType,proto3" json:"parameter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleParameterQuestion) Reset() {
	*x = SingleParameterQuestion{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleParameterQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleParameterQuestion) ProtoMessage() {}

func (x *SingleParameterQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleParameterQuestion.ProtoReflect.Descriptor instead.
func (*SingleParameterQuestion) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{7}
}

func (x *SingleParameterQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *SingleParameterQuestion) GetParameterType() string {
	if x != nil {
		return x.ParameterType
	}
	return ""
}

// MultipleParameterQuestion defines a question which prompts the user for one or several entities of one particular type
// Example: MultipleParameterQuestion(question_text='How old are your children?', parameter_type='sys.number')
type MultipleParameterQuestion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text which introduces the question (should be pronounceable)
	QuestionText string `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	// The display name of the entity (type) which is accepted as an answer to this question
	// Note: the corresponding entity_type must exist (system entity type) and is not automatically created
	ParameterType string `protobuf:"bytes,2,opt,name=parameter_type,json=parameterType,proto3" json:"parameter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleParameterQuestion) Reset() {
	*x = MultipleParameterQuestion{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleParameterQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleParameterQuestion) ProtoMessage() {}

func (x *MultipleParameterQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleParameterQuestion.ProtoReflect.Descriptor instead.
func (*MultipleParameterQuestion) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{8}
}

func (x *MultipleParameterQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *MultipleParameterQuestion) GetParameterType() string {
	if x != nil {
		return x.ParameterType
	}
	return ""
}

// The Choice message defines one "option" for the SingleChoiceQuestion and MultipleChoiceQuestion question types
// Example: Choice(synonyms=["blue", "blueish", "pale blue", "deep blue"])
type Choice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The synonyms which are recognized as equivalent for identifying one option
	Synonyms []string `protobuf:"bytes,1,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	// Optional; Nested question if this specific choice gets chosen.
	// Note: the follow-up question is only available for the SingleChoiceQuestion
	FollowUpQuestion *Question `protobuf:"bytes,2,opt,name=follow_up_question,json=followUpQuestion,proto3" json:"follow_up_question,omitempty"`
	// The "canonical value" (i.e. the entity value)
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{9}
}

func (x *Choice) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *Choice) GetFollowUpQuestion() *Question {
	if x != nil {
		return x.FollowUpQuestion
	}
	return nil
}

func (x *Choice) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Answer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the number of the question to which this answer belongs
	QuestionNr int64 `protobuf:"varint,1,opt,name=question_nr,json=questionNr,proto3" json:"question_nr,omitempty"`
	// the ID of the session on which the answer was collected
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Required; the full answer text
	AnswerText string `protobuf:"bytes,3,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	// fixme: better names and doc-strings below
	// Optional; contains the normalized value of the selected option (parameter) extracted
	AnswerParameter string `protobuf:"bytes,4,opt,name=answer_parameter,json=answerParameter,proto3" json:"answer_parameter,omitempty"`
	// Optional; contains the original text of the selected option (parameter) extracted
	AnswerParameterOriginal string `protobuf:"bytes,5,opt,name=answer_parameter_original,json=answerParameterOriginal,proto3" json:"answer_parameter_original,omitempty"`
	// Types that are valid to be assigned to IsAnonymous:
	//
	//	*Answer_Anonymous
	//	*Answer_UserInformation
	IsAnonymous   isAnswer_IsAnonymous `protobuf_oneof:"is_anonymous"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{10}
}

func (x *Answer) GetQuestionNr() int64 {
	if x != nil {
		return x.QuestionNr
	}
	return 0
}

func (x *Answer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Answer) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *Answer) GetAnswerParameter() string {
	if x != nil {
		return x.AnswerParameter
	}
	return ""
}

func (x *Answer) GetAnswerParameterOriginal() string {
	if x != nil {
		return x.AnswerParameterOriginal
	}
	return ""
}

func (x *Answer) GetIsAnonymous() isAnswer_IsAnonymous {
	if x != nil {
		return x.IsAnonymous
	}
	return nil
}

func (x *Answer) GetAnonymous() bool {
	if x != nil {
		if x, ok := x.IsAnonymous.(*Answer_Anonymous); ok {
			return x.Anonymous
		}
	}
	return false
}

func (x *Answer) GetUserInformation() *Answer_UserInfo {
	if x != nil {
		if x, ok := x.IsAnonymous.(*Answer_UserInformation); ok {
			return x.UserInformation
		}
	}
	return nil
}

type isAnswer_IsAnonymous interface {
	isAnswer_IsAnonymous()
}

type Answer_Anonymous struct {
	Anonymous bool `protobuf:"varint,7,opt,name=anonymous,proto3,oneof"`
}

type Answer_UserInformation struct {
	UserInformation *Answer_UserInfo `protobuf:"bytes,6,opt,name=user_information,json=userInformation,proto3,oneof"`
}

func (*Answer_Anonymous) isAnswer_IsAnonymous() {}

func (*Answer_UserInformation) isAnswer_IsAnonymous() {}

type CreateSurveyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Survey        *Survey                `protobuf:"bytes,1,opt,name=survey,proto3" json:"survey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSurveyRequest) Reset() {
	*x = CreateSurveyRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSurveyRequest) ProtoMessage() {}

func (x *CreateSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSurveyRequest.ProtoReflect.Descriptor instead.
func (*CreateSurveyRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSurveyRequest) GetSurvey() *Survey {
	if x != nil {
		return x.Survey
	}
	return nil
}

type GetSurveyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project identifier for this survey. Equal to the parent of the corresponding Agent.
	// Format: `projects/<Project ID>/agent`.
	SurveyId      string `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurveyRequest) Reset() {
	*x = GetSurveyRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurveyRequest) ProtoMessage() {}

func (x *GetSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurveyRequest.ProtoReflect.Descriptor instead.
func (*GetSurveyRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{12}
}

func (x *GetSurveyRequest) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

type UpdateSurveyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated survey. Note: the ID must refer to an existing survey which will be updated
	Survey *Survey `protobuf:"bytes,1,opt,name=survey,proto3" json:"survey,omitempty"`
	// Optional. Field mask that defines which fields get updated. Default: all fields are updated.
	// Example:
	//          - update_mask = FieldMask( [ 'survey.display_name', 'survey.questions' ] )
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSurveyRequest) Reset() {
	*x = UpdateSurveyRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSurveyRequest) ProtoMessage() {}

func (x *UpdateSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSurveyRequest.ProtoReflect.Descriptor instead.
func (*UpdateSurveyRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateSurveyRequest) GetSurvey() *Survey {
	if x != nil {
		return x.Survey
	}
	return nil
}

func (x *UpdateSurveyRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteSurveyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project identifier for this survey. Equal to the parent of the corresponding Agent.
	// Format: `projects/<Project ID>/agent`.
	SurveyId      string `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSurveyRequest) Reset() {
	*x = DeleteSurveyRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSurveyRequest) ProtoMessage() {}

func (x *DeleteSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSurveyRequest.ProtoReflect.Descriptor instead.
func (*DeleteSurveyRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSurveyRequest) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

type GetSurveyAnswersRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SurveyId string                 `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetSurveyAnswersRequest_SessionId
	//	*GetSurveyAnswersRequest_UserId
	//	*GetSurveyAnswersRequest_UserPhoneNumber
	Identifier    isGetSurveyAnswersRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSurveyAnswersRequest) Reset() {
	*x = GetSurveyAnswersRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSurveyAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSurveyAnswersRequest) ProtoMessage() {}

func (x *GetSurveyAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSurveyAnswersRequest.ProtoReflect.Descriptor instead.
func (*GetSurveyAnswersRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{15}
}

func (x *GetSurveyAnswersRequest) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *GetSurveyAnswersRequest) GetIdentifier() isGetSurveyAnswersRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetSurveyAnswersRequest) GetSessionId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetSurveyAnswersRequest_SessionId); ok {
			return x.SessionId
		}
	}
	return ""
}

func (x *GetSurveyAnswersRequest) GetUserId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetSurveyAnswersRequest_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *GetSurveyAnswersRequest) GetUserPhoneNumber() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetSurveyAnswersRequest_UserPhoneNumber); ok {
			return x.UserPhoneNumber
		}
	}
	return ""
}

type isGetSurveyAnswersRequest_Identifier interface {
	isGetSurveyAnswersRequest_Identifier()
}

type GetSurveyAnswersRequest_SessionId struct {
	// ID of one specific session on which survey answers were collected (contains survey_id)
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3,oneof"`
}

type GetSurveyAnswersRequest_UserId struct {
	// User Identifier. Note, if the survey is anonymous there will no identifier to filter on
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof"`
}

type GetSurveyAnswersRequest_UserPhoneNumber struct {
	// User phone number. Note, if the survey is anonymous there will no identifier to filter on
	UserPhoneNumber string `protobuf:"bytes,4,opt,name=user_phone_number,json=userPhoneNumber,proto3,oneof"`
}

func (*GetSurveyAnswersRequest_SessionId) isGetSurveyAnswersRequest_Identifier() {}

func (*GetSurveyAnswersRequest_UserId) isGetSurveyAnswersRequest_Identifier() {}

func (*GetSurveyAnswersRequest_UserPhoneNumber) isGetSurveyAnswersRequest_Identifier() {}

type GetAllSurveyAnswersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project identifier for this survey. Equal to the parent of the corresponding Agent.
	// Format: `projects/<Project ID>/agent`.
	SurveyId      string `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSurveyAnswersRequest) Reset() {
	*x = GetAllSurveyAnswersRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSurveyAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSurveyAnswersRequest) ProtoMessage() {}

func (x *GetAllSurveyAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSurveyAnswersRequest.ProtoReflect.Descriptor instead.
func (*GetAllSurveyAnswersRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllSurveyAnswersRequest) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

type SurveyAnswersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project identifier for this survey. Equal to the parent of the corresponding Agent.
	// Format: `projects/<Project ID>/agent`.
	SurveyId      string    `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	Answers       []*Answer `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"` // all requested answers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurveyAnswersResponse) Reset() {
	*x = SurveyAnswersResponse{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurveyAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurveyAnswersResponse) ProtoMessage() {}

func (x *SurveyAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurveyAnswersResponse.ProtoReflect.Descriptor instead.
func (*SurveyAnswersResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{17}
}

func (x *SurveyAnswersResponse) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

func (x *SurveyAnswersResponse) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type ListSurveysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The next_page_token value returned from a previous list request.
	// Example:
	//      "current_index-10--page_size-20"
	//      Start page -> 10
	//      Page size -> 20
	PageToken     string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveysRequest) Reset() {
	*x = ListSurveysRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveysRequest) ProtoMessage() {}

func (x *ListSurveysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveysRequest.ProtoReflect.Descriptor instead.
func (*ListSurveysRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{18}
}

func (x *ListSurveysRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// The response message for [Intents.ListIntents][google.cloud.dialogflow.v2.Intents.ListIntents].
type ListSurveysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of surveys. There will be a maximum number of items
	// returned based on the page_token field in the request.
	Surveys []*Survey `protobuf:"bytes,1,rep,name=surveys,proto3" json:"surveys,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSurveysResponse) Reset() {
	*x = ListSurveysResponse{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSurveysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSurveysResponse) ProtoMessage() {}

func (x *ListSurveysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSurveysResponse.ProtoReflect.Descriptor instead.
func (*ListSurveysResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{19}
}

func (x *ListSurveysResponse) GetSurveys() []*Survey {
	if x != nil {
		return x.Surveys
	}
	return nil
}

func (x *ListSurveysResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type AgentSurveyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project identifier for this survey. Equal to the parent of the corresponding Agent.
	// Format: `projects/<Project ID>/agent`.
	SurveyId      string `protobuf:"bytes,1,opt,name=survey_id,json=surveyId,proto3" json:"survey_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSurveyRequest) Reset() {
	*x = AgentSurveyRequest{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSurveyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSurveyRequest) ProtoMessage() {}

func (x *AgentSurveyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSurveyRequest.ProtoReflect.Descriptor instead.
func (*AgentSurveyRequest) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{20}
}

func (x *AgentSurveyRequest) GetSurveyId() string {
	if x != nil {
		return x.SurveyId
	}
	return ""
}

type AgentSurveyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent of an agent. Equal to the survey ID.
	// Format: `projects/<Project ID>/agent`.
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSurveyResponse) Reset() {
	*x = AgentSurveyResponse{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSurveyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSurveyResponse) ProtoMessage() {}

func (x *AgentSurveyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSurveyResponse.ProtoReflect.Descriptor instead.
func (*AgentSurveyResponse) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{21}
}

func (x *AgentSurveyResponse) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

type ScaleQuestion_ScaleValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleQuestion_ScaleValue) Reset() {
	*x = ScaleQuestion_ScaleValue{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleQuestion_ScaleValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleQuestion_ScaleValue) ProtoMessage() {}

func (x *ScaleQuestion_ScaleValue) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleQuestion_ScaleValue.ProtoReflect.Descriptor instead.
func (*ScaleQuestion_ScaleValue) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ScaleQuestion_ScaleValue) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ScaleQuestion_ScaleValue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Answer_UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First name of the User to be surveyed
	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Last name of the User to be surveyed
	LastName string `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Phone number of the User to be surveyed
	PhoneNumber string `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	// the ID of the session on which the answer was collected
	SessionId string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Unique identifier of the User to be surveyed
	UserId        string `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer_UserInfo) Reset() {
	*x = Answer_UserInfo{}
	mi := &file_ondewo_survey_survey_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer_UserInfo) ProtoMessage() {}

func (x *Answer_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ondewo_survey_survey_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer_UserInfo.ProtoReflect.Descriptor instead.
func (*Answer_UserInfo) Descriptor() ([]byte, []int) {
	return file_ondewo_survey_survey_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Answer_UserInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Answer_UserInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Answer_UserInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Answer_UserInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Answer_UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_ondewo_survey_survey_proto protoreflect.FileDescriptor

const file_ondewo_survey_survey_proto_rawDesc = "" +
	"\n" +
	"\x1aondewo/survey/survey.proto\x12\rondewo.survey\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"\xad\x03\n" +
	"\x06Survey\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rlanguage_code\x18\x03 \x01(\tR\flanguageCode\x125\n" +
	"\tquestions\x18\a \x03(\v2\x17.ondewo.survey.QuestionR\tquestions\x12:\n" +
	"\vsurvey_info\x18\b \x01(\v2\x19.ondewo.survey.SurveyInfoR\n" +
	"surveyInfo\x12A\n" +
	"\x10exclude_subflows\x18\t \x03(\x0e2\x16.ondewo.survey.SubFlowR\x0fexcludeSubflows\x129\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2!.ondewo.survey.Survey.AgentStatusR\x06status\"M\n" +
	"\vAgentStatus\x12\x15\n" +
	"\x11TO_BE_INITIALIZED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\f\n" +
	"\bUPDATING\x10\x02\x12\f\n" +
	"\bOUTDATED\x10\x03\"\xe5\x02\n" +
	"\n" +
	"SurveyInfo\x12!\n" +
	"\flegal_entity\x18\x01 \x01(\tR\vlegalEntity\x12%\n" +
	"\x0epostal_address\x18\x02 \x01(\tR\rpostalAddress\x12#\n" +
	"\remail_address\x18\x03 \x01(\tR\femailAddress\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x1f\n" +
	"\vphone_hours\x18\x05 \x01(\tR\n" +
	"phoneHours\x12+\n" +
	"\x11expected_duration\x18\x06 \x01(\tR\x10expectedDuration\x12\x18\n" +
	"\apurpose\x18\a \x01(\tR\apurpose\x12\x14\n" +
	"\x05topic\x18\b \x01(\tR\x05topic\x12)\n" +
	"\x10legal_disclaimer\x18\t \x01(\tR\x0flegalDisclaimer\x12\x1c\n" +
	"\tanonymous\x18\n" +
	" \x01(\bR\tanonymous\"\xb3\x04\n" +
	"\bQuestion\x12B\n" +
	"\ropen_question\x18\x01 \x01(\v2\x1b.ondewo.survey.OpenQuestionH\x00R\fopenQuestion\x12[\n" +
	"\x16single_choice_question\x18\x02 \x01(\v2#.ondewo.survey.SingleChoiceQuestionH\x00R\x14singleChoiceQuestion\x12a\n" +
	"\x18multiple_choice_question\x18\x03 \x01(\v2%.ondewo.survey.MultipleChoiceQuestionH\x00R\x16multipleChoiceQuestion\x12E\n" +
	"\x0escale_question\x18\x04 \x01(\v2\x1c.ondewo.survey.ScaleQuestionH\x00R\rscaleQuestion\x12d\n" +
	"\x19single_parameter_question\x18\x05 \x01(\v2&.ondewo.survey.SingleParameterQuestionH\x00R\x17singleParameterQuestion\x12j\n" +
	"\x1bmultiple_parameter_question\x18\x06 \x01(\v2(.ondewo.survey.MultipleParameterQuestionH\x00R\x19multipleParameterQuestionB\n" +
	"\n" +
	"\bquestion\"3\n" +
	"\fOpenQuestion\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\"l\n" +
	"\x14SingleChoiceQuestion\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\x12/\n" +
	"\achoices\x18\x02 \x03(\v2\x15.ondewo.survey.ChoiceR\achoices\"n\n" +
	"\x16MultipleChoiceQuestion\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\x12/\n" +
	"\achoices\x18\x02 \x03(\v2\x15.ondewo.survey.ChoiceR\achoices\"\xfa\x01\n" +
	"\rScaleQuestion\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\x12D\n" +
	"\tmin_value\x18\x02 \x01(\v2'.ondewo.survey.ScaleQuestion.ScaleValueR\bminValue\x12D\n" +
	"\tmax_value\x18\x03 \x01(\v2'.ondewo.survey.ScaleQuestion.ScaleValueR\bmaxValue\x1a8\n" +
	"\n" +
	"ScaleValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"e\n" +
	"\x17SingleParameterQuestion\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\x12%\n" +
	"\x0eparameter_type\x18\x02 \x01(\tR\rparameterType\"g\n" +
	"\x19MultipleParameterQuestion\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\x12%\n" +
	"\x0eparameter_type\x18\x02 \x01(\tR\rparameterType\"\x81\x01\n" +
	"\x06Choice\x12\x1a\n" +
	"\bsynonyms\x18\x01 \x03(\tR\bsynonyms\x12E\n" +
	"\x12follow_up_question\x18\x02 \x01(\v2\x17.ondewo.survey.QuestionR\x10followUpQuestion\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xf1\x03\n" +
	"\x06Answer\x12\x1f\n" +
	"\vquestion_nr\x18\x01 \x01(\x03R\n" +
	"questionNr\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vanswer_text\x18\x03 \x01(\tR\n" +
	"answerText\x12)\n" +
	"\x10answer_parameter\x18\x04 \x01(\tR\x0fanswerParameter\x12:\n" +
	"\x19answer_parameter_original\x18\x05 \x01(\tR\x17answerParameterOriginal\x12\x1e\n" +
	"\tanonymous\x18\a \x01(\bH\x00R\tanonymous\x12K\n" +
	"\x10user_information\x18\x06 \x01(\v2\x1e.ondewo.survey.Answer.UserInfoH\x00R\x0fuserInformation\x1a\xa1\x01\n" +
	"\bUserInfo\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userIdB\x0e\n" +
	"\fis_anonymous\"D\n" +
	"\x13CreateSurveyRequest\x12-\n" +
	"\x06survey\x18\x01 \x01(\v2\x15.ondewo.survey.SurveyR\x06survey\"/\n" +
	"\x10GetSurveyRequest\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\"\x81\x01\n" +
	"\x13UpdateSurveyRequest\x12-\n" +
	"\x06survey\x18\x01 \x01(\v2\x15.ondewo.survey.SurveyR\x06survey\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"2\n" +
	"\x13DeleteSurveyRequest\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\"\xae\x01\n" +
	"\x17GetSurveyAnswersRequest\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\x12\x1f\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tH\x00R\tsessionId\x12\x19\n" +
	"\auser_id\x18\x03 \x01(\tH\x00R\x06userId\x12,\n" +
	"\x11user_phone_number\x18\x04 \x01(\tH\x00R\x0fuserPhoneNumberB\f\n" +
	"\n" +
	"identifier\"9\n" +
	"\x1aGetAllSurveyAnswersRequest\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\"e\n" +
	"\x15SurveyAnswersResponse\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\x12/\n" +
	"\aanswers\x18\x02 \x03(\v2\x15.ondewo.survey.AnswerR\aanswers\"3\n" +
	"\x12ListSurveysRequest\x12\x1d\n" +
	"\n" +
	"page_token\x18\x01 \x01(\tR\tpageToken\"n\n" +
	"\x13ListSurveysResponse\x12/\n" +
	"\asurveys\x18\x01 \x03(\v2\x15.ondewo.survey.SurveyR\asurveys\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"1\n" +
	"\x12AgentSurveyRequest\x12\x1b\n" +
	"\tsurvey_id\x18\x01 \x01(\tR\bsurveyId\"-\n" +
	"\x13AgentSurveyResponse\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent*\xab\x01\n" +
	"\aSubFlow\x12\x17\n" +
	"\x13SUBFLOW_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03BOT\x10\x01\x12\x10\n" +
	"\fLEGAL_ENTITY\x10\x02\x12\x12\n" +
	"\x0ePOSTAL_ADDRESS\x10\x03\x12\x11\n" +
	"\rEMAIL_ADDRESS\x10\x04\x12\x10\n" +
	"\fPHONE_NUMBER\x10\x05\x12\x0f\n" +
	"\vPHONE_HOURS\x10\x06\x12\x15\n" +
	"\x11EXPECTED_DURATION\x10\a\x12\v\n" +
	"\aPURPOSE\x10\b2\xbb\t\n" +
	"\aSurveys\x12]\n" +
	"\fCreateSurvey\x12\".ondewo.survey.CreateSurveyRequest\x1a\x15.ondewo.survey.Survey\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/survey\x12b\n" +
	"\tGetSurvey\x12\x1f.ondewo.survey.GetSurveyRequest\x1a\x15.ondewo.survey.Survey\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/survey/{survey_id=*}\x12k\n" +
	"\fUpdateSurvey\x12\".ondewo.survey.UpdateSurveyRequest\x1a\x15.ondewo.survey.Survey\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/survey/{survey_id=*}\x12i\n" +
	"\fDeleteSurvey\x12\".ondewo.survey.DeleteSurveyRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/survey/{survey_id=*}\x12f\n" +
	"\vListSurveys\x12!.ondewo.survey.ListSurveysRequest\x1a\".ondewo.survey.ListSurveysResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/surveys\x12\x96\x01\n" +
	"\x10GetSurveyAnswers\x12&.ondewo.survey.GetSurveyAnswersRequest\x1a$.ondewo.survey.SurveyAnswersResponse\"4\x82\xd3\xe4\x93\x02.\x12,/survey/{survey_id=*}/answers/{session_id=*}\x12\x8d\x01\n" +
	"\x13GetAllSurveyAnswers\x12).ondewo.survey.GetAllSurveyAnswersRequest\x1a$.ondewo.survey.SurveyAnswersResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/survey/{survey_id=*}/answers\x12\x82\x01\n" +
	"\x11CreateAgentSurvey\x12!.ondewo.survey.AgentSurveyRequest\x1a\".ondewo.survey.AgentSurveyResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/survey/{survey_id=*}/agent\x12\x82\x01\n" +
	"\x11UpdateAgentSurvey\x12!.ondewo.survey.AgentSurveyRequest\x1a\".ondewo.survey.AgentSurveyResponse\"&\x82\xd3\xe4\x93\x02 :\x01*2\x1b/survey/{survey_id=*}/agent\x12z\n" +
	"\x11DeleteAgentSurvey\x12!.ondewo.survey.AgentSurveyRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$*\"/survey/{survey_id=*}/agent/deleteb\x06proto3"

var (
	file_ondewo_survey_survey_proto_rawDescOnce sync.Once
	file_ondewo_survey_survey_proto_rawDescData []byte
)

func file_ondewo_survey_survey_proto_rawDescGZIP() []byte {
	file_ondewo_survey_survey_proto_rawDescOnce.Do(func() {
		file_ondewo_survey_survey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ondewo_survey_survey_proto_rawDesc), len(file_ondewo_survey_survey_proto_rawDesc)))
	})
	return file_ondewo_survey_survey_proto_rawDescData
}

var file_ondewo_survey_survey_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ondewo_survey_survey_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_ondewo_survey_survey_proto_goTypes = []any{
	(SubFlow)(0),                       // 0: ondewo.survey.SubFlow
	(Survey_AgentStatus)(0),            // 1: ondewo.survey.Survey.AgentStatus
	(*Survey)(nil),                     // 2: ondewo.survey.Survey
	(*SurveyInfo)(nil),                 // 3: ondewo.survey.SurveyInfo
	(*Question)(nil),                   // 4: ondewo.survey.Question
	(*OpenQuestion)(nil),               // 5: ondewo.survey.OpenQuestion
	(*SingleChoiceQuestion)(nil),       // 6: ondewo.survey.SingleChoiceQuestion
	(*MultipleChoiceQuestion)(nil),     // 7: ondewo.survey.MultipleChoiceQuestion
	(*ScaleQuestion)(nil),              // 8: ondewo.survey.ScaleQuestion
	(*SingleParameterQuestion)(nil),    // 9: ondewo.survey.SingleParameterQuestion
	(*MultipleParameterQuestion)(nil),  // 10: ondewo.survey.MultipleParameterQuestion
	(*Choice)(nil),                     // 11: ondewo.survey.Choice
	(*Answer)(nil),                     // 12: ondewo.survey.Answer
	(*CreateSurveyRequest)(nil),        // 13: ondewo.survey.CreateSurveyRequest
	(*GetSurveyRequest)(nil),           // 14: ondewo.survey.GetSurveyRequest
	(*UpdateSurveyRequest)(nil),        // 15: ondewo.survey.UpdateSurveyRequest
	(*DeleteSurveyRequest)(nil),        // 16: ondewo.survey.DeleteSurveyRequest
	(*GetSurveyAnswersRequest)(nil),    // 17: ondewo.survey.GetSurveyAnswersRequest
	(*GetAllSurveyAnswersRequest)(nil), // 18: ondewo.survey.GetAllSurveyAnswersRequest
	(*SurveyAnswersResponse)(nil),      // 19: ondewo.survey.SurveyAnswersResponse
	(*ListSurveysRequest)(nil),         // 20: ondewo.survey.ListSurveysRequest
	(*ListSurveysResponse)(nil),        // 21: ondewo.survey.ListSurveysResponse
	(*AgentSurveyRequest)(nil),         // 22: ondewo.survey.AgentSurveyRequest
	(*AgentSurveyResponse)(nil),        // 23: ondewo.survey.AgentSurveyResponse
	(*ScaleQuestion_ScaleValue)(nil),   // 24: ondewo.survey.ScaleQuestion.ScaleValue
	(*Answer_UserInfo)(nil),            // 25: ondewo.survey.Answer.UserInfo
	(*fieldmaskpb.FieldMask)(nil),      // 26: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),              // 27: google.protobuf.Empty
}
var file_ondewo_survey_survey_proto_depIdxs = []int32{
	4,  // 0: ondewo.survey.Survey.questions:type_name -> ondewo.survey.Question
	3,  // 1: ondewo.survey.Survey.survey_info:type_name -> ondewo.survey.SurveyInfo
	0,  // 2: ondewo.survey.Survey.exclude_subflows:type_name -> ondewo.survey.SubFlow
	1,  // 3: ondewo.survey.Survey.status:type_name -> ondewo.survey.Survey.AgentStatus
	5,  // 4: ondewo.survey.Question.open_question:type_name -> ondewo.survey.OpenQuestion
	6,  // 5: ondewo.survey.Question.single_choice_question:type_name -> ondewo.survey.SingleChoiceQuestion
	7,  // 6: ondewo.survey.Question.multiple_choice_question:type_name -> ondewo.survey.MultipleChoiceQuestion
	8,  // 7: ondewo.survey.Question.scale_question:type_name -> ondewo.survey.ScaleQuestion
	9,  // 8: ondewo.survey.Question.single_parameter_question:type_name -> ondewo.survey.SingleParameterQuestion
	10, // 9: ondewo.survey.Question.multiple_parameter_question:type_name -> ondewo.survey.MultipleParameterQuestion
	11, // 10: ondewo.survey.SingleChoiceQuestion.choices:type_name -> ondewo.survey.Choice
	11, // 11: ondewo.survey.MultipleChoiceQuestion.choices:type_name -> ondewo.survey.Choice
	24, // 12: ondewo.survey.ScaleQuestion.min_value:type_name -> ondewo.survey.ScaleQuestion.ScaleValue
	24, // 13: ondewo.survey.ScaleQuestion.max_value:type_name -> ondewo.survey.ScaleQuestion.ScaleValue
	4,  // 14: ondewo.survey.Choice.follow_up_question:type_name -> ondewo.survey.Question
	25, // 15: ondewo.survey.Answer.user_information:type_name -> ondewo.survey.Answer.UserInfo
	2,  // 16: ondewo.survey.CreateSurveyRequest.survey:type_name -> ondewo.survey.Survey
	2,  // 17: ondewo.survey.UpdateSurveyRequest.survey:type_name -> ondewo.survey.Survey
	26, // 18: ondewo.survey.UpdateSurveyRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 19: ondewo.survey.SurveyAnswersResponse.answers:type_name -> ondewo.survey.Answer
	2,  // 20: ondewo.survey.ListSurveysResponse.surveys:type_name -> ondewo.survey.Survey
	13, // 21: ondewo.survey.Surveys.CreateSurvey:input_type -> ondewo.survey.CreateSurveyRequest
	14, // 22: ondewo.survey.Surveys.GetSurvey:input_type -> ondewo.survey.GetSurveyRequest
	15, // 23: ondewo.survey.Surveys.UpdateSurvey:input_type -> ondewo.survey.UpdateSurveyRequest
	16, // 24: ondewo.survey.Surveys.DeleteSurvey:input_type -> ondewo.survey.DeleteSurveyRequest
	20, // 25: ondewo.survey.Surveys.ListSurveys:input_type -> ondewo.survey.ListSurveysRequest
	17, // 26: ondewo.survey.Surveys.GetSurveyAnswers:input_type -> ondewo.survey.GetSurveyAnswersRequest
	18, // 27: ondewo.survey.Surveys.GetAllSurveyAnswers:input_type -> ondewo.survey.GetAllSurveyAnswersRequest
	22, // 28: ondewo.survey.Surveys.CreateAgentSurvey:input_type -> ondewo.survey.AgentSurveyRequest
	22, // 29: ondewo.survey.Surveys.UpdateAgentSurvey:input_type -> ondewo.survey.AgentSurveyRequest
	22, // 30: ondewo.survey.Surveys.DeleteAgentSurvey:input_type -> ondewo.survey.AgentSurveyRequest
	2,  // 31: ondewo.survey.Surveys.CreateSurvey:output_type -> ondewo.survey.Survey
	2,  // 32: ondewo.survey.Surveys.GetSurvey:output_type -> ondewo.survey.Survey
	2,  // 33: ondewo.survey.Surveys.UpdateSurvey:output_type -> ondewo.survey.Survey
	27, // 34: ondewo.survey.Surveys.DeleteSurvey:output_type -> google.protobuf.Empty
	21, // 35: ondewo.survey.Surveys.ListSurveys:output_type -> ondewo.survey.ListSurveysResponse
	19, // 36: ondewo.survey.Surveys.GetSurveyAnswers:output_type -> ondewo.survey.SurveyAnswersResponse
	19, // 37: ondewo.survey.Surveys.GetAllSurveyAnswers:output_type -> ondewo.survey.SurveyAnswersResponse
	23, // 38: ondewo.survey.Surveys.CreateAgentSurvey:output_type -> ondewo.survey.AgentSurveyResponse
	23, // 39: ondewo.survey.Surveys.UpdateAgentSurvey:output_type -> ondewo.survey.AgentSurveyResponse
	27, // 40: ondewo.survey.Surveys.DeleteAgentSurvey:output_type -> google.protobuf.Empty
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_ondewo_survey_survey_proto_init() }
func file_ondewo_survey_survey_proto_init() {
	if File_ondewo_survey_survey_proto != nil {
		return
	}
	file_ondewo_survey_survey_proto_msgTypes[2].OneofWrappers = []any{
		(*Question_OpenQuestion)(nil),
		(*Question_SingleChoiceQuestion)(nil),
		(*Question_MultipleChoiceQuestion)(nil),
		(*Question_ScaleQuestion)(nil),
		(*Question_SingleParameterQuestion)(nil),
		(*Question_MultipleParameterQuestion)(nil),
	}
	file_ondewo_survey_survey_proto_msgTypes[10].OneofWrappers = []any{
		(*Answer_Anonymous)(nil),
		(*Answer_UserInformation)(nil),
	}
	file_ondewo_survey_survey_proto_msgTypes[15].OneofWrappers = []any{
		(*GetSurveyAnswersRequest_SessionId)(nil),
		(*GetSurveyAnswersRequest_UserId)(nil),
		(*GetSurveyAnswersRequest_UserPhoneNumber)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ondewo_survey_survey_proto_rawDesc), len(file_ondewo_survey_survey_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ondewo_survey_survey_proto_goTypes,
		DependencyIndexes: file_ondewo_survey_survey_proto_depIdxs,
		EnumInfos:         file_ondewo_survey_survey_proto_enumTypes,
		MessageInfos:      file_ondewo_survey_survey_proto_msgTypes,
	}.Build()
	File_ondewo_survey_survey_proto = out.File
	file_ondewo_survey_survey_proto_goTypes = nil
	file_ondewo_survey_survey_proto_depIdxs = nil
}
