// Copyright 2020 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License. (editesyntax = "proto3";

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.32.0
// source: ondewo/survey/survey.proto

package survey

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Surveys_CreateSurvey_FullMethodName        = "/ondewo.survey.Surveys/CreateSurvey"
	Surveys_GetSurvey_FullMethodName           = "/ondewo.survey.Surveys/GetSurvey"
	Surveys_UpdateSurvey_FullMethodName        = "/ondewo.survey.Surveys/UpdateSurvey"
	Surveys_DeleteSurvey_FullMethodName        = "/ondewo.survey.Surveys/DeleteSurvey"
	Surveys_ListSurveys_FullMethodName         = "/ondewo.survey.Surveys/ListSurveys"
	Surveys_GetSurveyAnswers_FullMethodName    = "/ondewo.survey.Surveys/GetSurveyAnswers"
	Surveys_GetAllSurveyAnswers_FullMethodName = "/ondewo.survey.Surveys/GetAllSurveyAnswers"
	Surveys_CreateAgentSurvey_FullMethodName   = "/ondewo.survey.Surveys/CreateAgentSurvey"
	Surveys_UpdateAgentSurvey_FullMethodName   = "/ondewo.survey.Surveys/UpdateAgentSurvey"
	Surveys_DeleteAgentSurvey_FullMethodName   = "/ondewo.survey.Surveys/DeleteAgentSurvey"
)

// SurveysClient is the client API for Surveys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SurveysClient interface {
	// Create a Survey and an empty NLU Agent for it
	CreateSurvey(ctx context.Context, in *CreateSurveyRequest, opts ...grpc.CallOption) (*Survey, error)
	// Retrieve a Survey message from the Database and return it
	GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*Survey, error)
	// Update an existing Survey message from the Database and return it
	UpdateSurvey(ctx context.Context, in *UpdateSurveyRequest, opts ...grpc.CallOption) (*Survey, error)
	// Delete a survey and its associated agent (if existent)
	DeleteSurvey(ctx context.Context, in *DeleteSurveyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Returns the list of all surveys in the server
	ListSurveys(ctx context.Context, in *ListSurveysRequest, opts ...grpc.CallOption) (*ListSurveysResponse, error)
	// Retrieve answers to survey questions collected in interactions with a survey agent for a specific session
	GetSurveyAnswers(ctx context.Context, in *GetSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyAnswersResponse, error)
	// Retrieve all answers to survey questions collected in interactions with a survey agent in any session
	GetAllSurveyAnswers(ctx context.Context, in *GetAllSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyAnswersResponse, error)
	// Populate and configures an NLU Agent from a Survey
	CreateAgentSurvey(ctx context.Context, in *AgentSurveyRequest, opts ...grpc.CallOption) (*AgentSurveyResponse, error)
	// Update an NLU agent from a survey
	UpdateAgentSurvey(ctx context.Context, in *AgentSurveyRequest, opts ...grpc.CallOption) (*AgentSurveyResponse, error)
	// Deletes all data of an NLU agent associated to a survey
	DeleteAgentSurvey(ctx context.Context, in *AgentSurveyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type surveysClient struct {
	cc grpc.ClientConnInterface
}

func NewSurveysClient(cc grpc.ClientConnInterface) SurveysClient {
	return &surveysClient{cc}
}

func (c *surveysClient) CreateSurvey(ctx context.Context, in *CreateSurveyRequest, opts ...grpc.CallOption) (*Survey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Survey)
	err := c.cc.Invoke(ctx, Surveys_CreateSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) GetSurvey(ctx context.Context, in *GetSurveyRequest, opts ...grpc.CallOption) (*Survey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Survey)
	err := c.cc.Invoke(ctx, Surveys_GetSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) UpdateSurvey(ctx context.Context, in *UpdateSurveyRequest, opts ...grpc.CallOption) (*Survey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Survey)
	err := c.cc.Invoke(ctx, Surveys_UpdateSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) DeleteSurvey(ctx context.Context, in *DeleteSurveyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Surveys_DeleteSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) ListSurveys(ctx context.Context, in *ListSurveysRequest, opts ...grpc.CallOption) (*ListSurveysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSurveysResponse)
	err := c.cc.Invoke(ctx, Surveys_ListSurveys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) GetSurveyAnswers(ctx context.Context, in *GetSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyAnswersResponse)
	err := c.cc.Invoke(ctx, Surveys_GetSurveyAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) GetAllSurveyAnswers(ctx context.Context, in *GetAllSurveyAnswersRequest, opts ...grpc.CallOption) (*SurveyAnswersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurveyAnswersResponse)
	err := c.cc.Invoke(ctx, Surveys_GetAllSurveyAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) CreateAgentSurvey(ctx context.Context, in *AgentSurveyRequest, opts ...grpc.CallOption) (*AgentSurveyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSurveyResponse)
	err := c.cc.Invoke(ctx, Surveys_CreateAgentSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) UpdateAgentSurvey(ctx context.Context, in *AgentSurveyRequest, opts ...grpc.CallOption) (*AgentSurveyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSurveyResponse)
	err := c.cc.Invoke(ctx, Surveys_UpdateAgentSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *surveysClient) DeleteAgentSurvey(ctx context.Context, in *AgentSurveyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Surveys_DeleteAgentSurvey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SurveysServer is the server API for Surveys service.
// All implementations must embed UnimplementedSurveysServer
// for forward compatibility.
type SurveysServer interface {
	// Create a Survey and an empty NLU Agent for it
	CreateSurvey(context.Context, *CreateSurveyRequest) (*Survey, error)
	// Retrieve a Survey message from the Database and return it
	GetSurvey(context.Context, *GetSurveyRequest) (*Survey, error)
	// Update an existing Survey message from the Database and return it
	UpdateSurvey(context.Context, *UpdateSurveyRequest) (*Survey, error)
	// Delete a survey and its associated agent (if existent)
	DeleteSurvey(context.Context, *DeleteSurveyRequest) (*emptypb.Empty, error)
	// Returns the list of all surveys in the server
	ListSurveys(context.Context, *ListSurveysRequest) (*ListSurveysResponse, error)
	// Retrieve answers to survey questions collected in interactions with a survey agent for a specific session
	GetSurveyAnswers(context.Context, *GetSurveyAnswersRequest) (*SurveyAnswersResponse, error)
	// Retrieve all answers to survey questions collected in interactions with a survey agent in any session
	GetAllSurveyAnswers(context.Context, *GetAllSurveyAnswersRequest) (*SurveyAnswersResponse, error)
	// Populate and configures an NLU Agent from a Survey
	CreateAgentSurvey(context.Context, *AgentSurveyRequest) (*AgentSurveyResponse, error)
	// Update an NLU agent from a survey
	UpdateAgentSurvey(context.Context, *AgentSurveyRequest) (*AgentSurveyResponse, error)
	// Deletes all data of an NLU agent associated to a survey
	DeleteAgentSurvey(context.Context, *AgentSurveyRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSurveysServer()
}

// UnimplementedSurveysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSurveysServer struct{}

func (UnimplementedSurveysServer) CreateSurvey(context.Context, *CreateSurveyRequest) (*Survey, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSurvey not implemented")
}
func (UnimplementedSurveysServer) GetSurvey(context.Context, *GetSurveyRequest) (*Survey, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSurvey not implemented")
}
func (UnimplementedSurveysServer) UpdateSurvey(context.Context, *UpdateSurveyRequest) (*Survey, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSurvey not implemented")
}
func (UnimplementedSurveysServer) DeleteSurvey(context.Context, *DeleteSurveyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSurvey not implemented")
}
func (UnimplementedSurveysServer) ListSurveys(context.Context, *ListSurveysRequest) (*ListSurveysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSurveys not implemented")
}
func (UnimplementedSurveysServer) GetSurveyAnswers(context.Context, *GetSurveyAnswersRequest) (*SurveyAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSurveyAnswers not implemented")
}
func (UnimplementedSurveysServer) GetAllSurveyAnswers(context.Context, *GetAllSurveyAnswersRequest) (*SurveyAnswersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSurveyAnswers not implemented")
}
func (UnimplementedSurveysServer) CreateAgentSurvey(context.Context, *AgentSurveyRequest) (*AgentSurveyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgentSurvey not implemented")
}
func (UnimplementedSurveysServer) UpdateAgentSurvey(context.Context, *AgentSurveyRequest) (*AgentSurveyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentSurvey not implemented")
}
func (UnimplementedSurveysServer) DeleteAgentSurvey(context.Context, *AgentSurveyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgentSurvey not implemented")
}
func (UnimplementedSurveysServer) mustEmbedUnimplementedSurveysServer() {}
func (UnimplementedSurveysServer) testEmbeddedByValue()                 {}

// UnsafeSurveysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SurveysServer will
// result in compilation errors.
type UnsafeSurveysServer interface {
	mustEmbedUnimplementedSurveysServer()
}

func RegisterSurveysServer(s grpc.ServiceRegistrar, srv SurveysServer) {
	// If the following call panics, it indicates UnimplementedSurveysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Surveys_ServiceDesc, srv)
}

func _Surveys_CreateSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).CreateSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_CreateSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).CreateSurvey(ctx, req.(*CreateSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_GetSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).GetSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_GetSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).GetSurvey(ctx, req.(*GetSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_UpdateSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).UpdateSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_UpdateSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).UpdateSurvey(ctx, req.(*UpdateSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_DeleteSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).DeleteSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_DeleteSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).DeleteSurvey(ctx, req.(*DeleteSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_ListSurveys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSurveysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).ListSurveys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_ListSurveys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).ListSurveys(ctx, req.(*ListSurveysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_GetSurveyAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSurveyAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).GetSurveyAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_GetSurveyAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).GetSurveyAnswers(ctx, req.(*GetSurveyAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_GetAllSurveyAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSurveyAnswersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).GetAllSurveyAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_GetAllSurveyAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).GetAllSurveyAnswers(ctx, req.(*GetAllSurveyAnswersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_CreateAgentSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).CreateAgentSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_CreateAgentSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).CreateAgentSurvey(ctx, req.(*AgentSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_UpdateAgentSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).UpdateAgentSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_UpdateAgentSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).UpdateAgentSurvey(ctx, req.(*AgentSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Surveys_DeleteAgentSurvey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentSurveyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SurveysServer).DeleteAgentSurvey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Surveys_DeleteAgentSurvey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SurveysServer).DeleteAgentSurvey(ctx, req.(*AgentSurveyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Surveys_ServiceDesc is the grpc.ServiceDesc for Surveys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Surveys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ondewo.survey.Surveys",
	HandlerType: (*SurveysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSurvey",
			Handler:    _Surveys_CreateSurvey_Handler,
		},
		{
			MethodName: "GetSurvey",
			Handler:    _Surveys_GetSurvey_Handler,
		},
		{
			MethodName: "UpdateSurvey",
			Handler:    _Surveys_UpdateSurvey_Handler,
		},
		{
			MethodName: "DeleteSurvey",
			Handler:    _Surveys_DeleteSurvey_Handler,
		},
		{
			MethodName: "ListSurveys",
			Handler:    _Surveys_ListSurveys_Handler,
		},
		{
			MethodName: "GetSurveyAnswers",
			Handler:    _Surveys_GetSurveyAnswers_Handler,
		},
		{
			MethodName: "GetAllSurveyAnswers",
			Handler:    _Surveys_GetAllSurveyAnswers_Handler,
		},
		{
			MethodName: "CreateAgentSurvey",
			Handler:    _Surveys_CreateAgentSurvey_Handler,
		},
		{
			MethodName: "UpdateAgentSurvey",
			Handler:    _Surveys_UpdateAgentSurvey_Handler,
		},
		{
			MethodName: "DeleteAgentSurvey",
			Handler:    _Surveys_DeleteAgentSurvey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ondewo/survey/survey.proto",
}
